### ISSUE TITLE
Add MIT LICENSE

### ISSUE THREAD

**Issue by vutran** [vutran/dext-default-theme#1]
- Add LICENSE file (see [dext](https://github.com/vutran/dext)) for file
- Add this badge to the README file: ![](https://img.shields.io/badge/license-MIT-blue.svg)

**Comment by AntPeixe** [comment]
Hi, would love to help, just need to check how to add the badge to the README

**Comment by vutran** [comment]
@AntPeixe 

I'd like to follow the style seen [here](https://raw.githubusercontent.com/vutran/dext/develop/README.md) and have it on a new line underneath the title and above the description.

---

### Example

<img width="489" alt="screen shot 2016-09-30 at 5 27 47 pm" src="https://cloud.githubusercontent.com/assets/1088312/19010328/3ca27c2a-8733-11e6-8218-46dbbe962d8a.png">

**Comment by AntPeixe** [comment]
#3
